language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gobjc gobjc++ libgnustep-base-dev libncurses-dev ninja-build
before_script: ./mk tests
script: ./pacmixer_run_tests
